- lib/css_parser/parser.rb
- test/test_css_parser_media_types.rb
This commit fixes a bug in CssParser::Parser#parse_block_into_rule_sets!
where the media_type was not being set for general rules that followed a
media query rule. This bug subsequently led to the result of
CssParser::Parser#to_s producing css strings that lacked these specific
rules, since that method organizes styles by media type.
The fix was to set the `current_media_queries` variable inside
`#parse_block_into_rule_sets!` back to `:all` after we finish iterating
through a media query, since that is the default state.
> Fix bug not setting general rules after media query

- Gemfile.lock
- lib/css_parser/parser.rb
- lib/css_parser/version.rb
... Along with also putting in a few cases not specified for brackets
Note: the base gem right now fails a single test (test_following_badly_escaped_import_rules), so this pull request fails that same test as well. So if it doesn't pass Travis CI, I would expect this is the reason.
> Fix regex for some things being malformed

- test/fixtures/import-malformed.css
- test/test_css_parser_loading.rb
I've added in a few tests to help with the malformed parsing from our most  recent changes.
> Added some tests to check for the malformed CSS in content blocks

- lib/css_parser/regexps.rb
- lib/css_parser/rule_set.rb
- test/test_rule_set_creating_shorthand.rb
- test/test_rule_set_expanding_shorthand.rb
The `background` property supports background size in addition to the other long-form properties. When we have a separate `background-size` property and when we create a shorthand version, we must include the `background-size` in the shorthand by preceding it with a  slash: `/` and vice versa—when we’re parsing a shorthand property, we must look for and fetch the `background-size` before we extract
`background-position` as otherwise it might be ambiguous.
This should fix premailer/premailer#252 and premailer/premailer#216.
> Add support for background-size in the shorthand property

- lib/css_parser/rule_set.rb
- test/test_rule_set_creating_shorthand.rb
The latest release of css_parser introduction a bug when creating shorthand for background. If there is a background-size, but not a background-position, there is a ruby error `undefined local variable or method 'value'`
value was missing a colon, it should be a symbol not a variable. I fixed this and added a test for this case.
> fix bug when there is no background-position but a background-size when creating shorthand

- lib/css_parser/rule_set.rb
- test/test_rule_set_creating_shorthand.rb
- test/test_rule_set_expanding_shorthand.rb
Hi guys, there seem to have been a bug, where `border-color: #000 #fff` etc... wasn't correctly expanded. This PR aims to fix this. I've also included some test cases.
Hope this fix can be merged.
P.S. not entirely sure why  `test_following_badly_escaped_import_rules` is failing in `test/test_css_parser_loading.rb`. Also, do I need to include version bump commit in this PR?
> Border shorthand expand fixes + tests

- lib/css_parser/parser.rb
Requests the new URL instead. This might need some polishing or
modifications.
**Edit:** To elaborate, I was scraping some HTML pages for stylesheets and tried to parse the files. On a certain site, I received a status code 302. The stylesheet had been moved, and css_parser threw an error. This patch requests the new location instead and returns that.
> Added support for http status code redirects

- lib/css_parser/parser.rb
- lib/css_parser/rule_set.rb
- test/test_css_parser_misc.rb
Extra whitespace in form of multiple spaces, tabs, line feeds, carriage returns and form feeds within CSS selectors and in queries might not be a beauty. But as I understand the spec, multiple elements within a selector should be "whitespace-separated", and it includes all those kinds of whitespaces. [¹](#footnote1)
This topic branched pull request adds tests and support for both selectors and queries with extra whitespace by normalizing it.
<a name="footnote1">[1]</a>: https://www.w3.org/TR/css3-selectors/#selector-syntax
> Normalize whitespace in selectors and queries

- lib/css_parser/rule_set.rb
- test/test_rule_set_creating_shorthand.rb
The use of the `initial` keyword as the value for the `background-position` in the background shorthand is causing the CSS to be invalid (at least in every browser I was able to test). Using the [stated default](http://www.w3schools.com/cssref/pr_background-position.asp) of `0% 0%` instead resolves the issue.
You can see the issue in action in this [Codepen](http://codepen.io/ehlertij/pen/bBoqBE). Open the inspector to see the broken CSS:
My company ran into the issue after upgrading to the latest version of the gem and had to roll it back to before this was introduced as a result. Issue was introduced in #65 and #66.
Let me know if you need anything else from me on this one.
**Update:**
According to [this page on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/background#Formal_synt …
> Fix use of inital value for background-position in shorthand.

- Gemfile.lock
- lib/css_parser/parser.rb
- lib/css_parser/version.rb
- test/test_css_parser_basic.rb
```
.-  m\
(( ` /|\   /|
__.'/    /'_
,.^"--'_-'|  /(//
)))) |\ ) !/   )
((((  `E)|/    (
/ \ `    )
/ ' \ `  (
/  '  \  `)
/   '     (\
/   ______.' \
/_.-' /_/    \_\
/, '-.__    (_`__
```
ejm  |`_
> Add: to_h Instance Method Returning CSS As A Hash

- lib/css_parser/rule_set.rb
- test/test_rule_set_creating_shorthand.rb
This PR prevents css_parser to convert single declarations to their respective shorthand.
So, if there is a single declaration in a selector like `background-color: #fff;`, it won't be converted to `background: #fff` and thus it won't overwrite declarations like `background-image` on other css rules.
> Do not short single properties

- lib/css_parser/rule_set.rb
- test/test_rule_set_expanding_shorthand.rb
While attempting use Premailer to inline CSS for emails originating from Amazon, we started seeing errors when expanding font shorthands that have spaces after the forward slash - e.g `font-size/ line-height`:
```
NoMethodError: undefined method `strip' for nil:NilClass
/bundle/gems/css_parser-1.5.0/lib/css_parser/rule_set.rb:99:in `block in each_declaration'
/bundle/gems/css_parser-1.5.0/lib/css_parser/rule_set.rb:97:in `each'
/bundle/gems/css_parser-1.5.0/lib/css_parser/rule_set.rb:97:in `each_declaration'
/bundle/gems/css_parser-1.5.0/lib/css_parser.rb:81:in `block in merge'
/bundle/gems/css_parser-1.5.0/lib/css_parser.rb:69:in `each'
/bundle/gems/css_parser-1.5.0/lib/css_parser.rb:69:in `merge'
...
```
An example of the email body particulars:
```
...
a {
text-decoration: none;
color: …
```
> Handles font-size/ line-height shorthand with spaces

- lib/css_parser/parser.rb
- test/test_css_parser_misc.rb
(I was working with css_parser today, wanted to `parser.each_selector.collect { ...`, but it raised `LocalJumpError`.)
> Parser#each_selector returns Enumerator if not given block

- lib/css_parser.rb
- lib/css_parser/parser.rb
- lib/css_parser/regexps.rb
- lib/css_parser/rule_set.rb
Tested on ruby 2.3.1 ( with https://dialect.ca/inc/screen.css ) for https://github.com/premailer/css_parser/issues/92
Script 
```
require 'memory_profiler'
report = MemoryProfiler.report do
CssParser::Parser.new.load_uri!("file:///home/*****/Documents/screen.css")
end
report.pretty_print
```
Previous
```
Total allocated: 2208154 bytes (23505 objects)
Total retained:  0 bytes (0 objects)
allocated memory by gem
-----------------------------------
2200965  css_parser/lib
7037  addressable-2.5.2
152  other
allocated memory by file
-----------------------------------
1570459  /home/anmol/Documents/work/css_parser/lib/css_parser/parser.rb
609546  /home/anmol/Documents/work/css_parser/lib/css_parser/rule_set.rb
20960  /home/anmol/Documents/work/css_parser/lib/css_parser.rb
7037 …
```
> Memory and Performance Optimization

- lib/css_parser/rule_set.rb
While using the `premailer` gem with a background worker, I noticed that our excessive GC was slowing our mail jobs down. The main culprit, is this gem. 
I took 3 approaches to reducing allocations and memory usage.
1. reduce dynamic string creation for border properties. (This can also be done for `expand_dimensions_shorthand`
2. Reduced hash allocations
3. Reduces string allocations when parsing a complex document. 
Overall, allocated memory was reduced by 25% and object allocation was reduced by 27%. 
```
Total allocated: 6873180 bytes (96310 objects)
Total retained:  5585 bytes (58 objects)
allocated memory by gem
-----------------------------------
6861148  css_parser/lib
10776  racc
1256  other
allocated objects by class
-----------------------------------
57903  String
20809  Array …
```
> Reduce Allocations to reduce memory usage

- css_parser.gemspec
This inserts the direct links to changelog/bugs in RubyGems. It also allows easier automatic processing of updates.
> Provide metadata for RubyGems

- lib/css_parser/parser.rb
- test/test_css_parser_misc.rb
The line changed was causing UTF-8 chars to be stripped out in the CSS parsing. UTF-8 chars are needed for 'font-family' of Asian fonts. Not sure why binary encoding was used here previously.
```
font-family: "Helvetica Neue","Microsoft YaHei UI","Microsoft YaHei New","Microsoft YaHei","微软雅黑","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji",sans-serif,system-ui;
```
> Force UTF-8 encoding; do not strip out UTF-8 chars.

- CHANGELOG.md
From what I see this was the only relevant change:
https://github.com/premailer/css_parser/compare/v1.7.0..v1.7.1
> Add v1.7.1 to changelog

- .travis.yml
* Removes deprecated 'sudo: false' option.
* Only defines MAJOR.MINOR version so the latest available version
will be picked.
> Add testing with Ruby 2.7 to CI

- lib/css_parser/regexps.rb
Flags are not applied if regexp is passed to `Regexp.new`
`lib/css_parser/regexps.rb:23: warning: flags ignored`
Fixes 2d228d14
> Fixup flags on RE_URI

- Gemfile.lock
- Rakefile
- css_parser.gemspec
- lib/css_parser/rule_set.rb
- test/rule_set/test_declaration_value.rb
Also fix rake task, `.join('test/fixtures')` returns invalid absolute path.
Extract from https://github.com/premailer/css_parser/pull/115.
`bundle exec rake benchmark` results
Before:
```
Executing: bundle exec rake benchmark
Warming up --------------------------------------
import1.css loading   363.000  i/100ms
complex.css loading    16.000  i/100ms
Calculating -------------------------------------
import1.css loading      4.087k (± 3.6%) i/s -     20.691k in   5.069769s
complex.css loading    160.094  (± 6.9%) i/s -    800.000  in   5.026577s
Loading `import1.css` allocated 348 objects, 25 KiB
Loading `complex.css` allocated 9111 objects, 704 KiB
```
After:
```
Executing: bundle exec rake benchmark
Warming up --------------------------------------
import1.css loading   410.000  i/100ms …
```
> Fixup benchmark & add `RuleSet::DeclarationValue`

- Rakefile
- lib/css_parser/rule_set.rb
- test/rule_set/declarations/test_value.rb
I noticed that new tests are not run on `bundle exec rake test` without explicit `TEST=` :facepalm: 
Also `#==` in `Value` is really needed since identical value are unequal without it.
> Fix `RuleSet::Declarations` tests and actually run them

- lib/css_parser/rule_set.rb
- test/rule_set/declarations/test_value.rb
- test/rule_set/test_declarations.rb
- test/test_rule_set_expanding_shorthand.rb
We can piggyback on `Hash` preserving it's order in all supported rubies & drop order. Looks quite ugly, but does the trick.
I assume that it will be faster if we'll properly track and propagate `order` in all places, but I suspect it will be also harder to work with.
And we're little faster at parsing because of `order` is removed:
Before:
```
Executing: bundle exec rake benchmark
Warming up --------------------------------------
import1.css loading   376.000  i/100ms
complex.css loading    14.000  i/100ms
Calculating -------------------------------------
import1.css loading      3.670k (± 3.6%) i/s -     18.424k in   5.027200s
complex.css loading    142.421  (± 4.2%) i/s -    714.000  in   5.021913s
Loading `import1.css` allocated 372 objects, 26 KiB
Loading `complex.css` allocated …
```
> Preserve rules priority while expanding shorthands

- .rubocop.yml
- Rakefile
- lib/css_parser/regexps.rb
- lib/css_parser/rule_set.rb
- test/test_css_parser_media_types.rb
> misc cleanup and improvements

- CHANGELOG.md
- lib/css_parser/regexps.rb
- lib/css_parser/rule_set.rb
- test/test_rule_set_expanding_shorthand.rb
Using CSS functions causes `CssParser::RuleSet#expand_dimensions_shorthand!` to raise an `ArgumentError`. What we attempt to do here is handle functions by using a temporary string replacement to sanely handle arguments like 
```css
margin: calc(1em / 4 * 2);
border: calc(var(--foo) / 2);
```
> Allow CSS functions to be used when expanding dimensions shorthand

- CHANGELOG.md
- lib/css_parser/rule_set.rb
- test/test_rule_set_creating_shorthand.rb
When having `border-width: 1px` and `border-color: black` but no `border-style` it would combine to an invalid, see https://codepen.io/dorianmariefr/pen/qBPqLZM for instance
Now it doesn't combine the properties if the three (width/color/style) are not present
I encountered this when doing `@apply border border-black` in tailwindcss and having it compiled by premailer for my emails, the border would not appear
> keep border-width when border-color has spaces

- CHANGELOG.md
- lib/css_parser/parser.rb
- test/test_css_parser_loading.rb
Add a new option `rule_set_exceptions` to silently swallow ArgumentErrors generated from RuleSet.
Related #125
> Allow rule set argument exceptions to be muted

- CHANGELOG.md
- lib/css_parser/rule_set.rb
- test/rule_set/declarations/test_value.rb
- test/rule_set/test_declarations.rb
Include the property in the ArgumentError returned by an empty value.
Spent several hours trying to trace this, having the property in the exception would have helped immensely.
Related #125
> Return the property value in an empty value rule set

- lib/css_parser/regexps.rb
Closes #133
Use of the third argument for `Regexp::new` is deprecated in Ruby 3.2.0.
> Move Regexp::new 3rd argument into 2nd

- lib/css_parser/rule_set.rb
- test/test_css_parser_misc.rb
Currently, parsing doesn't work properly for CSS rules with multiline URL values. Here's what happens:
```ruby
font_face = "@font-face {\n src: url(https://example.com/font.woff2), \n url(https://example.com/font.woff); } \n"
CssParser::Parser.new.tap { |parser| parser.add_block!(font_face) }.to_s
```
This is due to the regex here: https://github.com/premailer/css_parser/blob/57647747cb8b9eb517b0e70949b3e23b777645f5/lib/css_parser/rule_set.rb#L501
Amending this regex to `/(.[^:]*)\s*:\s*(?m:(.+))(;?\s*\Z)/i` (which essentially allows multiline capturing of a CSS rule's value capture group) fixes this issue.
I'm not a regex pro so I'm not sure if this is the best solution. Thoughts?
> Fix parsing of multiline URL values for rule sets

- .github/workflows/ci.yml
- CHANGELOG.md
- lib/css_parser/regexps.rb
For reasons I've not been smart enough to figure out, there's a difference in matching between 3.1 and 3.2
```ruby
RE_LENGTH_OR_PERCENTAGE =
Regexp.new('([\-]*(([0-9]*\.[0-9]+)|[0-9]+)(e[mx]+|px|[cm]+m|p[tc+]|in|\%))',
Regexp::IGNORECASE)
RE_BACKGROUND_POSITION = Regexp.new("((((#{RE_LENGTH_OR_PERCENTAGE})|left|center|right|top|bottom)[\s]*){1,2})", Regexp::IGNORECASE | Regexp::EXTENDED)
"  top right".match(RE_BACKGROUND_POSITION)
```
matches `top right` on ruby 3.1, but just `top ` on 3.2.
The previous regexp looked something like `/((top|right)\s*){1,2}/` to match 1 or 2 positions separated by optional whitespace.
This updates it to `/((top|right)\s+(top|right))|(top|right)/`, which seems to give consistent matching behaviour between ruby 3.1 & 3.2
> Fix parsing ruleset shorthands in ruby 3.2

- CHANGELOG.md
- lib/css_parser/parser.rb
- test/test_css_parser_media_types.rb
Previously, `@media (width:500px)` would be successfully parsed, but not `@media(width:500px)` - it would result in  `@media(width:500px)` as a single token, effectively ignoring the `media:500px` media-feature and assigning all the rules in that media query to the `:all` namespace.
This tokenizes `(` and `)` separately ... which naively seems ok to me and passes all the tests, but I'd confess to being a little nervous how it behaves with real-world CSS.
Fixes #139
> Fix parsing space-less media-features

- CHANGELOG.md
While viewing the CHANGELOG, I noticed what appears to be a typo.
> FIX: typo in  CHANGELOG.md

- CHANGELOG.md
- lib/css_parser/parser.rb
Added `user_agent` as an option to Parser to allow manually setting the user agent (closes #145).
> Added `user_agent` as an option to Parser

- css_parser.gemspec
Make the gem more secure by requiring that all privileged operations by any of the owners require OTP.
Ref: https://guides.rubygems.org/mfa-requirement-opt-in/
Why and what is being done.
> Opt-in for MFA requirement

- CHANGELOG.md
- lib/css_parser/parser.rb
If argument starts with a pipe character (`'|'`) and the receiver is the `IO` class, a subprocess is created in the same way as `Kernel#open`, and its output is returned. `Kernel#open` may allow unintentional command injection, which is the reason these `IO` methods are a security risk. Consider to use `File.read` to disable the behavior of subprocess invocation.
Ref: https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Security/IoMethods
Why and what is being done.
> Use File.read instead of IO.read

- CHANGELOG.md
I corrected a typo in the contents of CHANGELOG.md for version 1.17.1.
> fix: PR number typo in CHANGELOG.md

- .github/workflows/ci.yml
- .rubocop.yml
- CHANGELOG.md
- Gemfile.lock
- css_parser.gemspec
- lib/css_parser/parser.rb
- lib/css_parser/version.rb
> Drop Ruby 2.7 compatibility

- .github/workflows/ci.yml
- CHANGELOG.md
- Rakefile
- lib/css_parser/parser.rb
- lib/css_parser/rule_set.rb
- test/test_css_parser_basic.rb
- test/test_css_parser_loading.rb
- test/test_css_parser_media_types.rb
- test/test_css_parser_misc.rb
- test/test_merging.rb
- test/test_rule_set.rb
- test/test_rule_set_creating_shorthand.rb
- test/test_rule_set_expanding_shorthand.rb
I am working on solving #128. To get to know the code I did some changed which I think makes it overall better. 
I could try not to change anything else that what I absolutely have to but I think we will come better out of it if we make some more changes. Could you take a look at this changes and give me some pointer if you like this or not?
> Changes to creation of rule set

- Gemfile
- Gemfile.lock
- test/fixtures/dialect_ca_inc_screen.css
- test/test_css_parser_loading.rb
- test/test_css_parser_offset_capture.rb
- test/test_helper.rb
```
⋊> ~/D/c/t/fixtures on v2 ⨯ time be rake test                                                                                                                                                                                                               16:20:14
(in /Users/simon/Downloads/css_parser)
/Users/simon/.asdf/installs/ruby/3.2.2/bin/ruby -w -I"lib" /Users/simon/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.1/lib/rake/rake_test_loader.rb "test/rule_set/declarations/test_value.rb" "test/rule_set/test_declarations.rb" "test/test_css_parser_basic.rb" "test/test_css_parser_loading.rb" "test/test_css_parser_media_types.rb" "test/test_css_parser_misc.rb" "test/test_css_parser_offset_capture.rb" "test/test_css_parser_regexps.rb" "test/test_helper.rb" …
```
> Speed up test by webmock 22.53sec to 611.60 millis

- .rubocop.yml
- css_parser.gemspec
- lib/css_parser/parser.rb
- lib/css_parser/regexps.rb
- lib/css_parser/rule_set.rb
- lib/css_parser/rule_set/declarations.rb
- test/test_css_parser_misc.rb
- test/test_rule_set_expanding_shorthand.rb
I refactored expand_font_shorthand. I think its better. I think I want to do the same for all the other expand features. When I do that I think we can remove more of the regexes. Would you like that?
I am trying not to touch test too much to keep all existing features working.
Should I maybe add some notes into changelog that some features are removed?
> V2 rule set declaration parsing

- lib/css_parser/parser.rb
- lib/css_parser/rule_set.rb
- test/test_css_parser_misc.rb
- test/test_rule_set.rb
Fix #160
Why and what is being done.
> Fix selectors :not(.a,.b)

- CHANGELOG.md
- lib/css_parser/parser.rb
This PR replaces `scan` in `parse_block_into_rule_sets!` with `StringScanner` - a more performant API for tokenizing strings.
Tenderlove had a [post](https://tenderlovemaking.com/2023/09/02/fast-tokenizers-with-stringscanner/) last year about this.
On our benchmarks this shows a **18%** improvement in performance measured for overall `add_block!`. The code has been in production for around 3 years now, unfortunately making changes public takes additional effort.
> Use StringScanner instead of String#scan to improve block parsing performance

- CHANGELOG.md
- lib/css_parser/rule_set.rb
- test/test_rule_set.rb
This PR replaces regexp-matching code in `parse_declarations!` with equivalent substring lookup using `.split(&block)` and `.index`.
On our benchmarks this shows a 10% improvement in performance measured for _overall_ `add_rule!` / `add_block!`. So, quite a significant one.
> Improve parse_declarations! performance

- CHANGELOG.md
- lib/css_parser/rule_set.rb
- test/test_css_parser_misc.rb
- test/test_rule_set.rb
I haven't found a good justification for raising the error, and it helps a lot when parsing 3rd party CSS. It would still be raised when manually creating the declarations, and not parsing a block of CSS.
The performance impact is not noticable in my benchmarks... i also have a version that optimizes adding the declaration from parsed data, but it doesn't give any more than 3% speedup, so IMO the increased complexity wasn't worth it
Feel free to close if the error is valuable.
Coincidentally it also removes the sole use case for `rule_set_exceptions`, so i had to emulate the error in tests.
> Fix error when parsing values consisting of `!important` only

- .rubocop.yml
- lib/css_parser.rb
- lib/css_parser/parser.rb
- lib/css_parser/rule_set.rb
- test/test_css_parser_loading.rb
> fix perf copps

- CHANGELOG.md
- lib/css_parser/parser.rb
Maybe because of some false negatives affecting conditionals
Ref: rubocop/rubocop-performance#152
Why and what is being done.
> Fix `match?` that were not detected by RuboCop

- CHANGELOG.md
- lib/css_parser/rule_set.rb
- test/test_merging.rb
Previously, the css rule "color: black !important; color: red;" would be collapsed to "color: red;" as the processor did not take whether the !important flag was set inside the same rule.
This commit makes the Declaration Value initializer take notice of the !important flag and correctly handle it.
> Prefer !important rules over non-!important rules in the same ruleset
